name: nova_social
description: A new Flutter project.

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.2.1+15

environment:
  sdk: ">=2.17.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_web_plugins:
    sdk: flutter

  animated_text_kit: ^4.2.2
  any_link_preview: ^3.0.0
  cached_network_image: ^3.2.3
  carousel_slider: ^4.2.1
  cupertino_back_gesture: ^0.1.0
  cupertino_icons: ^1.0.5
  cloud_firestore: ^4.2.0
  cloud_functions: ^4.0.6
  collection: ^1.16.0
  connectivity_plus: ^3.0.2
  copy_with_extension: ^5.0.0
  crypto: ^3.0.2
  firebase_auth: ^4.2.0
  firebase_core: ^2.4.0
  firebase_crashlytics: ^3.0.7
  firebase_dynamic_links: ^5.1.0
  firebase_messaging: ^14.3.0
  firebase_storage: ^11.0.8
  flutter_cupertino_date_picker_fork: ^1.0.7
  flutter_local_notifications: ^13.0.0
  flutter_typeahead: ^4.3.7
  flutter_native_splash:
  flutter_reaction_button: ^2.0.1+2
  flutter_secure_storage: ^8.0.0
  flutter_staggered_grid_view: ^0.6.2
  flutter_svg:
  font_awesome_flutter: ^10.3.0
  freezed_annotation: ^2.2.0
  get_it: ^7.2.0
  google_fonts: ^3.0.1
  google_sign_in: ^5.4.2
  go_router: ^6.0.0
  gradient_borders: ^1.0.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  http: ^0.13.5
  iconify_flutter: ^0.0.5
  iconsax: ^0.0.8
  image_cropper: ^3.0.2
  image_picker: ^0.8.6+1
  image_picker_for_web: ^2.1.10
  internet_connection_checker: ^1.0.0+1
  intl: ^0.17.0
  json_serializable: ^6.5.4
  mime: ^1.0.4
  month_year_picker: ^0.2.0+2
  path_drawing: ^1.0.1
  profanity_filter: ^2.0.0
  provider: ^6.0.4
  readmore: ^2.2.0
  share_plus: ^6.3.1
  shared_preferences: ^2.0.15
  sign_in_with_apple: ^4.3.0
  universal_html: ^2.0.8
  url_launcher: ^6.1.7
  xml: ^6.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  # firebase_core_platform_interface: 4.5.1
  build_runner: ^2.2.0
  copy_with_extension_gen: ^5.0.0
  flutter_flavorizr: ^2.1.5
  flutter_lints: ^2.0.1
  flutter_launcher_icons: ^0.11.0
  hive_generator: any
  freezed: ^2.3.2
  package_rename: ^1.0.0+1

flavorizr:
  flavors:
    prod:
      app:
        name: "Nova Social"
      android:
        applicationId: "club.nova_social.android"
        firebase:
          config: "lib/config/firebase/prod/google-services.json"
      ios:
        bundleId: "club.novasocial.ios"
        firebase:
          config: "lib/config/firebase/prod/GoogleService-Info.plist"
    dev:
      app:
        name: "Nova Social Dev"
      android:
        applicationId: "club.nova_social.android.dev"
        firebase:
          config: "lib/config/firebase/dev/google-services.json"
      ios:
        bundleId: "club.novasocial.dev"
        firebase:
          config: "lib/config/firebase/dev/GoogleService-Info.plist"

package_rename_config:
  android:
    app_name: Nova Social
    package_name: club.nova_social.android

  ios:
    app_name: Nova Social
    bundle_name: nova-social
    package_name: club.novasocial.ios

  web:
    app_name: Nova Social
    description:

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/

  fonts:
    - family: CCClobberinTime
      fonts:
        - asset: assets/fonts/CCClobberinTimeSmooth.ttf
          style: normal

flutter_native_splash:
  color: "#1E1E1E"
  image: assets/images/nova_logo.png
  color_dark: "#1E1E1E"
  image_dark: assets/images/nova_logo.png

  android_12:
    image: assets/images/nova_logo.png
    icon_background_color: "#1E1E1E"
    image_dark: assets/images/nova_logo.png
    icon_background_color_dark: "#1E1E1E"

  web: false

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/nova_logo.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
