// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBocXm5oFmmhQO0CKSdyuxFe_jajNlgOok',
    appId: '1:899427589392:web:128815920fd1ea74451995',
    messagingSenderId: '899427589392',
    projectId: 'nova-social-b4f05',
    authDomain: 'nova-social-b4f05.firebaseapp.com',
    storageBucket: 'nova-social-b4f05.appspot.com',
    measurementId: 'G-0CH158QBDE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCtpmuDai8C8sXPGQjcsR1XTz5tiKkVtKA',
    appId: '1:899427589392:android:3a9b15c6a36c7ea4451995',
    messagingSenderId: '899427589392',
    projectId: 'nova-social-b4f05',
    storageBucket: 'nova-social-b4f05.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBXOTg7v_RH21UyTtg5y3S3z5EiEjBs_a4',
    appId: '1:899427589392:ios:1986a64ff296f0c9451995',
    messagingSenderId: '899427589392',
    projectId: 'nova-social-b4f05',
    storageBucket: 'nova-social-b4f05.appspot.com',
    iosClientId: '899427589392-0v1jiv4la1ejpfavdps29b7pe9srpbct.apps.googleusercontent.com',
    iosBundleId: 'com.example.novaSocial',
  );
}
